spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.10.3.32/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.1.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell
  port: 18080

wechat:
  mpAppId: wxb9b8ef133831adbe
  mpAppSecret: 22d95c1f0751d30e9f1919e674e6173c
  mchId: 1483469312
#  mchId: 1409146202
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: wx_cert/h5.p12
  notifyUrl: http://yxsell.nat300.top/sell/pay/notify
